[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "scikit-build>=0.16.7",
    "ninja",
    "setuptools>=46.4",
    "wheel",
	"Cython>=0.29.30,<3.0",
    "matplotlib",
    "meshio",
    "numpy==1.20.*; python_version <= '3.9'", # meshio undeclared constraint.
    "oldest-supported-numpy; python_version > '3.9'",
    "pyparsing",
    "scipy"
]
